### ISSUE TITLE
Dummy README with link to gitlab

### ISSUE THREAD

**Issue by ninsch3000** [zavolanlab/zarp#1]

**Comment by AngryMaciek** [comment]
Pushing anithing to this repo now is not a good idea since we will transfer another `git` repository from GitLab.  
Therefore please do not create any codebase in this address before the transfer. We would run into problems like: "How do we now append the real *zarp* repo at the end of the dummy *zarp* repo and keep the history intact?"  
However, you may specify all information you want here, as an issue.

**Comment by ninsch3000** [comment]
I'd only put a msg "Coming soon, currently still hosted on GitLab (link to gitlab)". That file wouldn't need to be saved in the history

**Comment by AngryMaciek** [comment]
Regardless of how big the file is you would like to push, we would still have the problem that you want o "append" one git repo (main zarp) at the end of another (dummy zarp). This is a bad strategy...

**Comment by uniqueg** [comment]
While it's true that you'd have two branches with different roots, there are plenty of ways to get around this problem, including:
- rebasing the ZARP commits onto @ninsch3000's initial commit
- force pushing an orphan branch (with no root) onto the default branch to bring it back to virgin state
- pushing the README with the redirection and the ZARP code base to different branches, set the default branch to the ZARP code base and (optionally) delete the "redirection branch"

**Comment by uniqueg** [comment]
Will migrate immediately
