### ISSUE TITLE
bug: issue with snakefmt in snakemake workflow catalog

### ISSUE THREAD

**Issue by fgypas** [zavolanlab/zarp#109]
**Describe the bug**
The snakefmt (version 0.8.0) check for zarp in the snakemake workflow catalog https://snakemake.github.io/snakemake-workflow-catalog/ is failing.

**Screenshots**

Here is what it shows
<img width="776" alt="Screenshot 2023-03-10 at 00 29 48" src="https://user-images.githubusercontent.com/6184370/224183977-f28827b5-0191-4cfb-b86b-e6590ec103da.png">

**Additional context**
The problem appeats in version 0.8.0 of snakefmt. See related issue: https://github.com/snakemake/snakefmt/issues/169

In our case is when we have multiple comment lines in the Snakefile

example:
```
# comment 1
# comment 2

rule X:
...
```

**Comment by uniqueg** [comment]
Agree that it is very likely the problem you link to. So perhaps we should ask at https://github.com/snakemake/snakemake-workflow-catalog to upgrade to `snakefmt` 0.8.1 ([pretty sure the bug was fixed there](https://github.com/snakemake/snakefmt/releases/tag/v0.8.1)) or higher?

Additionally, from our side, we should probably just remove consecutive comment lines. Not that we need them...
