### ISSUE TITLE
feat: sra download

### ISSUE THREAD

**Issue by ninsch3000** [zavolanlab/zarp#49]
Download run files from SRA.

**Describe the solution you'd like**
This download should NOT happen within core ZARP. Instead, a separate (small) snakemake pipeline will for now be created within the `workflow/rules/` directory, which can be called by ZARP-cli. At a later stage that pipeline might be migrated elsewhere.

Inputs:   
- SRR identifier OR SRA run table

Outputs:
- directory containing all downloaded SRR files    

See [related zarp-cli issue](https://github.com/zavolanlab/zarp-cli/issues/8)

**Comment by dominikburri** [comment]
The purpose of a separate snakemake pipeline is, that it can be paralellised and could run on a cluster. However, as @AngryMaciek, @ninsch3000 and @uniqueg pointed out, clusters (are generally) not connected to the internet.
So the rule must be executed locally. 

The problem of running multiple instances then likely becomes disk space. Raw fastq files are big and I'm not sure how `fasterq-dump` treats this and whether it creates lots of temporary files.

So my intuition is, that the benefit it lost and the download could be directly managed in zarp-cli within python calls.

**Comment by mkatsanto** [comment]
Hi just saw this issue. is there a reason why we do not wait for the pysradb repo issue to be fixed by the authors? From what they mention in the issue there this is a version instability. Why reinvent the wheel and not wait for some external help and focus on other issues? 
https://github.com/saketkc/pysradb/issues/155

**Comment by mzavolan** [comment]
The authors of pysradb have not gotten back to me with some idea of a time line. We are not reinventing any wheel, we just use instead the sra-toolkit to provide a minimal SRA functionality, i.e. access to fastq files for which accession numbers are known. fasterq-dump also allows the retrieval of paired end reads in separate files. I am not sure pysradb does that and in any case, we may return to it for more complex functionality (e.g. retrieval of data given project or sample group accessions). Finally, I don't think the pysradb deals with retries in case the donwload fails for some reason. That's one of the strongpoints of snakemake. The workflow will really be minimal, and would fit into the scheme of the other zarp-cli functionalities.

**Comment by mzavolan** [comment]
@ninsch3000 Please see above re: why snakemake and not Dominik's script. We need a simple snakemake workflow that takes a one-column file of accession numbers and calls fasterq-dump for each accession in the file, e.g. 
fasterq-dump -s ACCESSION  -O OUTPUT_DIR
Re @dominikburri's comment about space: fasterq-dump doesn't have an unnecessary temp file footprint. The files that are downloaded are the datafiles needed for analysis and if the user does not have space for them, then no analysis can be done. Again, a more complex logic can be implemented later, e.g. first query the metadata to see how large the files are, ask the user to confirm that they have the space for download and only the execute the download. But this is not an issue for a minimum viable version.

**Comment by dominikburri** [comment]
About the memory footprint of `fasterq-dump`: https://github.com/ncbi/sra-tools/wiki/HowTo%3A-fasterq-dump
> This temporary directory will use approximately up to 10 times the size of the final output-file.

Also, `gzip` has to be handled independently (same source as above). This is in comparison to `fastq-dump`

But they provide their own Docker image: https://hub.docker.com/r/ncbi/sra-tools. 
So I think we can clearly use it.

**Comment by dominikburri** [comment]
After discussion today, the workflow should have the following interfaces:

## Input

- tsv sample table in accordance with `zarp`, see [example](https://github.com/zavolanlab/zarp/blob/dev/tests/input_files/samples.tsv). 
  - In particular, column *sample* needs to be specified with SRR accession number.
  - If other samples are there, they are ignored (e.g. local samples). That is, samples names not matching `^SRR` are ignored.
- specification for where to download the samples. Currently, it is `sra_downloads`. 

## Output

- modified tsv table with columns *fq1* and *fq2* (if paired-end) filled with relative paths for the downloaded samples.
  - Are absolute paths also possible?

Is this the intended way? 
I guess the downside is, that the samples cannot be renamed and have to exactly match existing SRA accession numbers. After retrieving the files, renaming the column `samples` is possible though.

**Comment by dominikburri** [comment]
> Is this the intended way? I guess the downside is, that the samples cannot be renamed and have to exactly match existing SRA accession numbers. After retrieving the files, renaming the column `samples` is possible though.

Working example in commit 09dca28f076e00b50cf0bfd0f4c3cb7c1db88630

**Comment by dominikburri** [comment]
I tried to run the singularity version of SRA-tools with [this docker image](https://hub.docker.com/r/ncbi/sra-tools), see documentation [here](https://github.com/ncbi/sra-tools/wiki/SRA-tools-docker).
However, I get an error:
 ```
/.singularity.d/actions/exec: exec: line 21: bash: not found
```
when running snakemake with singularity. The call is something like `singularity exec SRATOOLS.simg bash`
When I replace `bash` by `sh`it is running successfully.
Now, I think this is because the base of the Docker image is very small and does not contain `bash`.

Can I tell snakemake to use `sh` instead of `bash`? Or should we build a docker image with `bash` on our own?
Maybe @fgypas or @uniqueg can tell me more?

**Comment by dominikburri** [comment]
@AngryMaciek and I found out that SRA-tools is built on [alpine](https://hub.docker.com/_/alpine), which does not contain `bash`.

**Comment by fgypas** [comment]
What about this `parallel-fastq-dump` that is available in bioconda: 

https://anaconda.org/bioconda/parallel-fastq-dump 
https://github.com/rvalieris/parallel-fastq-dump
https://quay.io/repository/biocontainers/parallel-fastq-dump?tab=tags

**Comment by AngryMaciek** [comment]
It might be worth a try but judging by the [build logs](https://hub.docker.com/layers/nunoagostinho/parallel-fastq-dump/latest/images/sha256-e5acbf355cd9f38e1943bb0a995139347f1d1a6562448f24237f3b7078d07372?context=explore) this one also uses `sh`:

**Comment by uniqueg** [comment]
So that would suggest that Snakemake cannot Singularity containers that do not include `bash`, so _every_ `alpine`-based and many other Docker images that do not come shipped with Bash. That's a serious limitation and I think we should check with Snakemake whether that's just an oversight, i.e., someone inadvertently wrote `bash` instead of `sh`, or whether there is really a requirement for Bash _and no other shell_.

One thing that should work is if it were possible to overwrite `bash` with an alias to `sh` or `ash`. I'm not quite sure what exactly calls what and how, so maybe that won't work, but perhaps it's worth a try (if Singularity actually calls `bash` then perhaps via `--singularity-args`?)

@AngryMaciek: `sh` isn't a shell itself, it's just a pointer to the default shell. For `alpine` that's usually `ash`, for my default user on my laptop (Ubuntu 20.04) that's `bash` - because it is set up like that in `/etc/passwd`. But `dash` is also installed by default and I could change my config to use that as the default shell. In that case, I could still run `bash` though - it just wouldn't be used by default or when running `sh`. So from the use of `sh` alone one cannot conclude which shells are installed. If Snakemake explicitly executes `bash`, it should work if Bash is installed, regardless of whether it's set as the default shell or not.

**Comment by ninsch3000** [comment]
Are you guys sure about Snakemake not working with Singularity/alpine? If so, it must be new, because one of my earliest containers, which is used in PolyAsite pipeline, is based on alpine: https://github.com/zavolanlab/Dockerfiles/blob/master/zavolab_minimal/3.7/Dockerfile

**Comment by uniqueg** [comment]
In any case I would suggest that you open an issue in Snakemake, because _at least_ they should document that only images are supported that have Bash installed. Also, they may know of other/better workarounds. Or they may decide to work towards supporting generic or at least multiple shells.

**Comment by mkatsanto** [comment]
Looked at this issue with the singularity implementation of sra-tools and the container was successfully installed. The issue seems rather to be connected to this issue: https://github.com/ncbi/sra-tools/issues/77
Somehow  you have to manually give permissions when you first install the sra-tools. 
No bash related error though in this container.
docker image:  
`docker://quay.io/biocontainers/sra-tools:2.11.0--pl5321ha49a11a_3`
error:
```
 This sra toolkit installation has not been configured.
Before continuing, please run: vdb-config --interactive
```

**Comment by mkatsanto** [comment]
Turns out if you make some mock .ncbi/user-settings.mkfg in the directory where you execute the workflow from it works without running the  vdb-config -i at all.
The issue remains that I am not sure in which path we should place this. In the example that worked I was triggering the test.local.sh in the sra test and added the lines seen below before running snakemake. 
Maybe we could make our own docker image with this workaround and use with singularity. This is similar to the workaround offered with conda.


```
echo """
/LIBS/GUID = \"randomuuid\"
/config/default = \"false\"
/repository/user/ad/public/apps/file/volumes/flatAd = \".\"
/repository/user/ad/public/apps/refseq/volumes/refseqAd = \".\"
/repository/user/ad/public/apps/sra/volumes/sraAd = \".\"
/repository/user/ad/public/apps/sraPileup/volumes/ad = \".\"
/repository/user/ad/public/apps/sraRealign/volumes/ad = \".\"
/repository/user/ad/public/apps/wgs/volumes/wgsAd = \".\"
/repository/user/ad/public/root = \".\"
/repository/user/default-path = \"$PWD/ncbi\"
""" > '.ncbi/user-settings.mkfg'
```
